# Generated by Django 5.0.6 on 2024-06-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0002_item_item_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_image",
            field=models.CharField(
                default="https://assets.epicurious.com/photos/568eb0bf7dc604b44b5355ee/16:9/w_2560%2Cc_limit/rice.jpg",
                max_length=500,
            ),
        ),
    ]
